spring:
  zipkin:
    base-url: http://54.254.30.227:9411
    enabled: false
  application:
    name: qpon-otp-service
    app-key: qpon-otp-c2cc3496-ccf8-4068-a83c-8q8p1o4n727b
  redis:
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    host: ${REDIS_HOST:qpon-prod-redis-ec.poc2a8.0001.aps1.cache.amazonaws.com}
    timeToLive: 60

## Eureka
eureka:
  client:
    service-url:
      defaultZone: https://api.qpon.lk/eureka

server:
  port: ${PORT:8082}
  servlet:
    context-path: /qpon-otp-service

ribbon:
  ReadTimeout: ${RIBBON_TIMEOUT:6000}

util:
  utilServiceAppKey: ${APP_KEY:ccus-c2cc3496-c9f8-4068-a83c-82841b44727b}
  baseUrl: ${UTIL_BASE_URL:https://api.qpon.lk/qpon-util-service}
  uri:
    sendMail: /api/v1/email/send
    sendSms: /api/v1/sms/send

header:
  timeZone:
    header: Time-Zone
    value: ${TIME_ZONE_VALUE:Asia/Colombo}
  appKey:
    header: app-key


accessControl:
  allowedOrigin: ${ALLOWED_ORIGIN:*}

logging:
  level:
    com.swivel.qpon.otp: DEBUG
